"""Add company to User model

Revision ID: f89100255b6a
Revises: 
Create Date: 2025-03-25 13:26:24.048269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89100255b6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Delivery', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('order_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('estimated_time',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        #batch_op.drop_constraint('fk_user_delivery', type_='foreignkey')
        batch_op.create_foreign_key('fk_user_delivery', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('Services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_info', sa.String(length=255), nullable=True))



    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('crm_contact_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('phone')
        batch_op.drop_column('image_file')
        batch_op.drop_column('is_crm_contact')
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_crm_contact', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=15), nullable=True))
        batch_op.alter_column('crm_contact_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=120),
               nullable=False)

   

    with op.batch_alter_table('Services', schema=None) as batch_op:
        batch_op.drop_column('additional_info')

    with op.batch_alter_table('Delivery', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'])
        batch_op.alter_column('estimated_time',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('order_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
